use md_parser::renderer::render_html;
use yew::prelude::*;

#[function_component(App)]
fn app() -> Html {
    let h = r"
    ## Header generated by Gohan

    This should [**have** a link](https://bpaulino.com/about) and fin.
    ";
    let html = render_html(h);
    let rendered_html = Html::from_html_unchecked(AttrValue::from(html.clone()));

    html! {
        <>
            <div>
                <h1 class="text-lg font-bold">{"Gohan - Markdown Parser"}</h1>
                <p>
                    {"Built with ❤️ by "}<a href="https://github.com/brunojppb" class="underline">{"Bruno Paulino"}</a>
                </p>
            </div>
            <div class="grid grid-cols-2 gap-8 mt-4">
                <h2>{"Markdown input"}</h2>
                <h2>{"HTML output"}</h2>
            </div>

            <div class="grid grid-cols-2 gap-8 mt-2">
            <textarea class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500"/>
            <article class="prose lg:prose-xl">
                {rendered_html}
            </article>
            </div>
        </>

    }
}

fn main() {
    yew::Renderer::<App>::new().render();
}
